# Build Matrix workflow for Android APKs
# - Fixed: invalid/empty "on:" and incorrect YAML indentation
# - Fixed: gradle assemble task requires capitalized variant (AssembleDebug/AssembleRelease).
#   Use matrix.include to map build-type -> gradleVariant (Debug/Release) so both task name
#   and artifact path (lowercase build-type) are correct.
# - Triggers: push and pull_request on "main" and manual workflow_dispatch (adjust branches as needed).
#
# References: /reference, https://docs.github.com/actions (CI basics and job matrix)
name: Build Matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      # Optional inputs for manual runs (not required by this matrix-based job,
      # but useful for external automation or documenting intended parameters).
      build_type:
        description: 'Optional: preferred build type (debug or release). Matrix still runs both variants by default.'
        required: false
        default: 'debug'
      note:
        description: 'Optional note for this manual run.'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - build-type: debug
            gradle-variant: Debug
          - build-type: release
            gradle-variant: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build ${{ matrix.build-type }} APK
        run: ./gradlew assemble${{ matrix.gradle-variant }}

      - name: Upload ${{ matrix.build-type }} APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build-type }}-apk
          path: app/build/outputs/apk/${{ matrix.build-type }}/WebLabs-MobIDE-${{ matrix.build-type }}.apk
