name: Flake8

on:
  push:
  pull_request:
    branches: ["master"]
    
jobs:
  Run:
    name: "Flake8"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install flake8
          python -m pip install flake8-github-actions

      - name: "Run Flake8"
        run: "flake8 --format github"















