name: Universal Mobile DevOps

on:
  push:
    branches: [WebOps, master]
  pull_request:
    branches: [WebOps, master]
  workflow_dispatch:

jobs:
  build-android:
    name: Android Build & Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ ('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build Android App
        run: ./gradlew assembleDebug

      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk

  test-python:
    name: Python Unit Tests & Dependency Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          if [ -f scripts/test.py ]; then python scripts/test.py; fi

  docker-image:
    name: Build & Push Docker Image (if Dockerfile detected)
    runs-on: ubuntu-latest
    if: ${{ always() && (hashFiles('Dockerfile') != '') }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ github.repository }}:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag ${{ github.repository }}:latest ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest

  artifact-sweep:
    name: Sweep & Archive Common Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Archive models, deps, and manifests
        uses: actions/upload-artifact@v4
        with:
          name: repo-artifacts
          path: |
            ai/downloads/**
            ai/deps/**
            ai/download_manifest.json
            app/build/outputs/apk/debug/*.apk
            dist/**
            build/**
            output/**
        continue-on-error: true
