name: Development Environment Setup
 
dependencies:  
 on:
  ubuntu:
     - git-lfs
     - jq

 steps:
   - name: Install Git LFS
     run: |
       sudo apt-get update -y
       sudo apt-get install -y git-lfs
       git lfs install --system

   - name: Clone Hugging Face Model
     inputs:
       model_repo:
        description: "Hugging Face repository to clone"
        default: "Salesforce/codet5-small"
        
    run: 
         git clone https://huggingface.co/Salesforce/codet5-small
         echo "Model cloned to %s"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-lfs=2.13.3 jq=1.6
          git lfs install --system
        shell: bash

      - name: Clone Hugging Face Model
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
          MODEL_REPO: "Salesforce/codet5-small"
        run: |
          if [[ -z "$HUGGINGFACE_TOKEN" ]]; then
            echo "Error: Missing Hugging Face token."
            exit 1
          fi
          git clone https://user:${HUGGINGFACE_TOKEN}@huggingface.co/${MODEL_REPO} model_repo
          echo "Model cloned to $(pwd)/model_repo"
        shell: bash 
