name: Super-Coder-Lab

on:
  workflow_dispatch:
    inputs:
      model_repo:
        description: 'Hugging Face repo'
        default: 'Salesforce/codet5-small'
        required: true
      vendor_path:
        description: 'Path to vendor model into repo'
        default: 'app/src/main/assets/models/codet5-small'
        required: true
      target_branch:
        description: 'Branch to operate on'
        default: 'WebOps'
        required: true
      commit_mode:
        description: 'Commit directly or open PR'
        default: 'commit'
        required: true
      build_apk:
        description: 'Build APK after vendoring'
        default: 'true'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-lfs jq
          git lfs install --system
