name: Super-Coder-Lab

on:
  workflow_dispatch:
    inputs:
      model_repo:
        description: 'Hugging Face repo'
        default: 'Salesforce/codet5-small'
        required: true
      vendor_path:
        description: 'Path to vendor model into repo'
        default: 'app/src/main/assets/models/codet5-small'
        required: true
      target_branch:
        description: 'Branch to operate on'
        default: 'WebOps'
        required: true
      commit_mode:
        description: 'Commit directly or open PR'
        default: 'commit'
        required: true
      build_apk:
        description: 'Build APK after vendoring'
        default: 'true'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-lfs jq
          git lfs install --system

  vendor:
    name: Vendor Model
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Vendor Hugging Face model
        run: git clone https://huggingface.co/${{ github.event.inputs.model_repo }} ${{ github.event.inputs.vendor_path }}

      - name: Normalize .gitattributes for LFS
        run: |
          if ! grep -q "*.bin filter=lfs" .gitattributes; then
            echo "*.bin filter=lfs diff=lfs merge=lfs -text" >> .gitattributes
            echo "*.safetensors filter=lfs diff=lfs merge=lfs -text" >> .gitattributes
            echo "*.pt filter=lfs diff=lfs merge=lfs -text" >> .gitattributes
            echo "*.onnx filter=lfs diff=lfs merge=lfs -text" >> .gitattributes
            echo "*.tflite filter=lfs diff=lfs merge=lfs -text" >> .gitattributes
          fi
          git add .gitattributes

      - name: Strip upstream git metadata from vendored model
        run: find "${{ github.event.inputs.vendor_path }}" -maxdepth 3 -type d -name ".git" -exec rm -rf {} +

      - name: Minimal model hygiene pass
        run: |
          find "${{ github.event.inputs.vendor_path }}" -type d -name ".cache" -prune -exec rm -rf {} +
          find "${{ github.event.inputs.vendor_path }}" -type f -exec chmod 0644 {} +

  commit:
    name: Commit Changes
    runs-on: ubuntu-latest
    needs: vendor

    steps:
      - name: Commit changes
        run: |
          git checkout -b fix/weblabs-codelab-${{ github.run_id }}
          git add "${{ github.event.inputs.vendor_path }}"
          git commit -m "Vendor ${{ github.event.inputs.model_repo }} into ${{ github.event.inputs.vendor_path }} [LFS]"
          git push --set-upstream origin HEAD

      - name: Create Pull Request
        if: ${{ github.event.inputs.commit_mode == 'pr' }}
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pull } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Vendor ${process.env.MODEL_REPO} into ${process.env.VENDOR_PATH} [LFS]`,
              head: `fix/weblabs-codelab-${{ github.run_id }}`,
              base: process.env.TARGET_BRANCH,
              body: 'Automated vendoring of models and configuration files.'
            });
            console.log(`Created PR: ${pull.html_url}`);

      - name: Direct Commit
        if: ${{ github.event.inputs.commit_mode == 'commit' }}
        run: git merge HEAD

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: commit
    if: ${{ github.event.inputs.build_apk == 'true' }}

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: weblabs-mobide-apk
          path: build/outputs/apk/**/*.apk
