name: DeepCode/Snyk Autonomous Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  snyk-code-review:
    name: Snyk Code Analysis (DeepCode)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Code Analysis
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test --json > snyk-code-results.json

      - name: Upload Snyk Results
        uses: actions/upload-artifact@v4
        with:
          name: snyk-code-results
          path: snyk-code-results.json
